name: Reviw Rover 1.0.0

on:
  issues:
    types:
      - opened
      - edited

jobs:
  create-zip:
    runs-on: ubuntu-latest
    steps:
      - name: Paso 1
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.Reviw_Rover_Token }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments \
          -d '{
            "body": "Hola, gracias por crear este Issue. Vas a crear un archivo JWPUB nuevo o es una consulta:\n\n- Responde **/Y** si crearás un archivo JWPUB nuevo. \n- Responde **/N** si solo es una consulta."
          }'
      
      - name: Esperar respuesta del usuario
        id: wait-for-user-response
        run: echo "Esperando respuesta del usuario..."

      - name: Paso 2
        run: |
          comment_body=$(jq -r '.comment.body' ${{ github.event.client_payload_path }})

          # Comprobar si el comentario contiene la respuesta "/Y"
          if [[ "$comment_body" == *"/Y"* ]]; then
            curl -X POST -H "Authorization: token ${{ secrets.Reviw_Rover_Token }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments \
              -d '{
                "body": "Hola, gracias por crear este Issue. Por favor, proporciona los siguientes datos para generar el archivo ZIP:\n\n- repositoryURL: \n- language: \n- symbol: \n- year: "
              }'
          else
            echo "De acuerdo, dime en qué podemos ayudarte."
          fi
