name: Reviw Rover 1.0.0 - Step 1

on:
  issue_comment:
    types:
      - opened
      - edited

jobs:
  create-zip:
    runs-on: ubuntu-latest
    steps:
      - name: Paso 1
        run: |
            curl -X POST -H "Authorization: token ${{ secrets.Reviw_Rover_Token }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments \
            -d '{
              "body": "Hola, gracias por crear este Issue. Vas a crear un archivo JWPUB nuevo o es una consulta:\n\n- Responde "/Sí" si crearás un archivo JWPUB nuevo. \n- Responde "/No" si solo es una consulta."
            }'
