name: Crear ZIP en respuesta a nuevo Issue

on:
  issue_comment:
    types:
      - created
      - edited

jobs:
  create-zip:
    if: startsWith(github.event.comment.body, '/inicia')  # Verificar que el comentario comienza con '/inicia'
    runs-on: ubuntu-latest
    steps:
      - name: Verificar etiqueta
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.Reviw_Rover_Token }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments \
          -d '{
            "body": "Hola, gracias por crear este Issue. Por favor, proporciona los siguientes datos para generar el archivo ZIP:\n\n- repositoryURL: \n- language: \n- symbol: \n- year: "
          }'
      
      - name: Esperar respuesta del usuario
        id: wait-for-user-response
        run: echo "Esperando respuesta del usuario..."
